### ISSUE TITLE
pre-trained models

### ISSUE THREAD

**Issue by AmirMz1** [linYDTHU/DesnowNet_Context-Aware_Deep_Network_for_Snow_Removal#1]
Hi, thank you for sharing this reop.
the link you shared for pre-trained models doesn't work. can you provide a new link to the pre-trained models?

@linYDTHU

**Comment by linYDTHU** [comment]
Hi, thanks for your interest in this repo. However, I just graduated from Tsinghua University, so I lost the access to my pretrained models.  

The repo is easily reproduced following the instructions in README. You can run the experiment on your device and save your own checkpoints.
